# Diamond Atari Games
type = "Diamond"
entrypoint = "diamond_csgo.dweam_game:CSGOGame"
repo_link = "https://github.com/eloialonso/diamond"
thumbnail_dir = "thumbnails"

# Game-specific metadata
[games.csgo]
title = "Counter-Strike: Global Offensive"
tags = ["First Person"]
description = "Tactical FPS game"

[games.csgo.buttons]
"â¬†ï¸ Forward" = "W"
"â¬‡ï¸ Back" = "S"
"â¬…ï¸ Left" = "A"
"â¡ï¸ Right" = "D"
"ğŸ†™ Jump" = "Space"
"ğŸ¦µ Crouch" = "Ctrl"
"ğŸ‘Ÿ Walk" = "Shift"
"1ï¸âƒ£ Weapon 1" = "1"
"2ï¸âƒ£ Weapon 2" = "2"
"3ï¸âƒ£ Weapon 3" = "3"
"ğŸ”„ Reload" = "R"
"ğŸ”« Shoot" = "Mouse Left Click"
"ğŸ” Aim" = "Mouse Right Click"
"ğŸ–±ï¸ Move Camera" = "Mouse Movement"
"ğŸ”¼ Camera Up" = "Arrow Up"
"â–¶ï¸ Camera Right" = "Arrow Right"
"â—€ï¸ Camera Left" = "Arrow Left"
"ğŸ”½ Camera Down" = "Arrow Down"